classes : ['drink','food','snack','cutlery','container','cleaning_stuff','fruit']
unknown: []
drink: ['aquarius','coke','cold_brew','green_tea']
food: ['bread','corn','onion','radish']
snack: ['candy','chewing_gum','cup_star','curry','fries','jelly']
cutlery: ['chopsticks','fork','spoon']
container: ['bowl','plate','soup_container']
cleaning_stuff: ['asience','hair_spray','moisturizer','shampoo']
fruit: ['apple','orange']

unknown_location: waste_bin
drink_location: kitchen_counter
food_location: kitchen_shelf
snack_location: kitchen_rack
cutlery_location: sideboard
container_location: left_rack
cleaning_stuff_location: right_rack
fruit_location: balcony_shelf

places: ['bedroom','kitchen','living_room','balcony','corridor','entrance']
bedroom: ['little_desk','teepee','bed']
kitchen: ['sideboard','kitchen_table']
living_room: ['desk','left_rack','right_rack','bookcase','sofa','coffee_table','TV']
balcony: ['bistro_table','left_planks','right_planck','balcony_shelf']
corridor: []
entrance: ['entrance_shelf']

bedroom_doors: '1'
kitchen_doors: '1'
living_room_doors: '1'
balcony_doors: '0'
corridor_doors: '0'
entrance_doors: '1'

bedroom_table: '0'
kitchen_table: '1'
living_room_table: '1'
balcony_table: '1'
corridor_table: '0'
entrance_table: '0'

bedroom_chairs: 0
kitchen_chairs: '6'
living_room_chairs: 0
balcony_chairs: '2'
corridor_chairs: 0
entrance_chairs: 0

classes_colour : ['blue','red','yellow','black','white']
blue: ['hair_spray',cold_brew','shampoo','cup_star']
red: ['fries','apple','asience','bowl','bread','candy',]
yellow: ['green_tea','onion','orange','corn']
black: ['coke','soup_container','jelly']
white: ['aquarius','moisturizer','radish','chewing_gum','chopsticks','curry','fork','spoon','plate']

size: ['spoon','forks','chopsticks','apple','onion','orange','candies','jelly','chewing_gum','soup_container']
weigth: ['forks','spoon','chopsticks','apple','orange','onion','aquarius','shampoo','hair_spray','coke','asience','green_tea']

drink_smallest: 'cold_brew'
drink_biggest:  'aquarius'
drink_lightest: 'cold_brew'
drink_heaviest: 'aquarius' 

food_smallest: 'onion'
food_biggest: 'food'
food_lightest: 'apple'
food_heaviest: 'orange'

snack_smallest: 'onion'
snack_biggest: 'bread'
snack_lightest: 'onion'
snack_heaviest: 'radish'

cutlery_smallest: 'spoon'
cutlery_biggest: 'chopsticks'
cutlery_lightest: 'forks'
cutlery_heaviest: 'chopsticks'

container_smallest: 'soup_container'
container_biggest: 'plate'
container_lightest: 'soup_container'
container_heaviest: 'bowl'

cleaning_stuff_smallest:  
cleaning_stuff_biggest: shampoo
cleaning_stuff_lightest: 
cleaning_stuff_heaviest: shampoo

fruit_smallest: 'apple'
fruit_biggest: 'orange'
fruit_lightest: 'apple'
fruit_heaviest: 'orange'

object_smallest: spoon
object_biggest: plate
object_lightest: fork
object_heaviest: aquarius
