classes : ['drinks','food','snacks','cutlery','containers','cleaning_stuff','fruit']
unknown: []
drinks: []
food: []
snacks: []
cutlery: []
containers: []
cleaning_stuff: []
fruit: []

unknown_location: 
drinks_location: 
food_location: 
snacks_location: 
cutlery_location: 
containers_location: 
cleaning_stuff_location: 
fruit_location: 

places: ['bedroom','kitchen','living_room','balcony','corridor','entrance']
bedroom: []
kitchen: []
living_room: []
balcony: []
corridor: []
entrance: []

bedroom_doors: '3'
kitchen_doors: '3'
living_room_doors: '3'
balcony_doors: '3'
corridor_doors: '3'
entrance_doors: '3'

bedroom_table: '3'
kitchen_table: '3'
living_room_table: '3'
balcony_table: '3'
corridor_table: '3'
entrance_table: '3'

bedroom_chairs: '3'
kitchen_chairs: '3'
living_room_chairs: '3'
balcony_chairs: '3'
corridor_chairs: '3'
entrance_chairs: '3'

classes_colour : ['blue','red','yellow','black','white']
blue: []
red: []
yellow: []
black: []
white: []

size: []
weigth: []

unknown_class: unknown
unknown_smallest: 
unknown_biggest: 
unknown_lightest: 
unknown_heaviest: 
drinks_smallest: 
drinks_biggest: 
drinks_lightest: 
drinks_heaviest: 
food_smallest: 
food_biggest: 
food_lightest: 
food_heaviest: 
snacks_smallest: 
snacks_biggest: 
snacks_lightest: 
snacks_heaviest: 
cutlery_smallest: 
cutlery_biggest: 
cutlery_lightest: 
cutlery_heaviest: 
containers_smallest: 
containers_biggest: 
containers_lightest: 
containers_heaviest: 
cleaning_stuff_smallest: 
cleaning_stuff_biggest: 
cleaning_stuff_lightest: 
cleaning_stuff_heaviest: 
fruit_smallest: 
fruit_biggest: 
fruit_lightest: 
fruit_heaviest: 
object_smallest: 
object_biggest: 
object_lightest: 
object_heaviest: 
