classes : ["drinks","food","snacks","toiletries","containers","candies"]

drinks : ["tea","beer","coke","sake"]
food : ["noodles","apple","paprika","melon","sushi","flakes","oat"]
snacks : ["chips","senbei","pringles","peanuts"]
candies : ["chocolate_bar","manju","mints","chocolate_egg"]
toiletries: ["shampoo","soap","cloth","sponge"]
containers: ["bowl","mug","glass","tray","plate","box","bag"]


unknown: []
unknown_location: waste_bin
drinks_location: bar
food_location: fridge
snacks_location: desk
toiletries_location: cupboard 
containers_location: counter
candies_location: center_table


places: ["bedroom","kitchen","living_room","office","corridor","bathroom"]
manipulation_places: ["bar","fridge","desk","cupboard","counter","center_table","living_shelf","bedside","tv_stand","living_table","drawer","sink","sideshelf","bookcase","dining_table","fridge","cabinet","couch_table","dinner_table","kitchen_counter","kitchen_table"]
big_object: ["sofa","bed","chairs","plant","bar","fridge","desk","cupboard","counter","center_table","living_shelf","bedside","tv_stand","living_table","drawer","sink","sideshelf","bookcase","dinnig_table","fridge","cabinet","couch_table","dinner_table","kitchen_counter","kitchen_table"]

bedroom: ["bed","bedside"]
living_room: ["living_shelf","tv_stand","center_table","living_table","bar"]
office: ["drawer","desk"]
kitchen: ["sink","sideshelf","bookcase","dining_table","fridge","counter","kitchen_counter"]
corridor : ["cabinet"]
bathroom : ["cupboard"]

kitchen_doors: "1"
living_room_doors: "2"
dining_doors: "3"
bedroom_doors: "4"
office_doors: "5"
bathroom_doors: "6"
corridor_doors: "2"

kitchen_table: "1"
living_table: "2"
dining_table: "3"
bedroom_table: "4"
office_table: "5"
bathroom_table: "6"
corridor_table: "6"

kitchen_chairs: "1"
living_chairs: "2"
dining_chairs: "3"
bedroom_chairs: "4"
office_chairs: "5"
bathroom_chairs: "6"
corridor_chairs: "6"

classes_colour : ["blue","red","yellow","black","white"]
blue: ["flakes","chips","senbei","pringles","peanuts"]
yellow: ["chocolate_bar","manju","mints","chocolate_egg","shampoo","soap","cloth"]
black: ["tea","beer","coke","sake","noodles","apple","melon","sushi"]
white: ["sponge","bowl","mug","glass","tray","plate","box","bag"]
red: ["oat","paprika"]

size: ["tea","beer","coke","sake","noodles","apple","paprika","melon","sushi","flakes","oat","chips","senbei","pringles","peanuts","chocolate_bar","manju","mints","chocolate_egg","shampoo","soap","cloth","sponge","bowl","mug","glass","tray","plate","box","bag"]
weigth: ["tea","beer","coke","sake","noodles","apple","paprika","melon","sushi","flakes","oat","chips","senbei","pringles","peanuts","chocolate_bar","manju","mints","chocolate_egg","shampoo","soap","cloth","sponge","bowl","mug","glass","tray","plate","box","bag"]

unknown_class: unknown
food_smallest: paprika
food_biggest: melon
food_lightest: chips
food_heaviest: apple
drink_smallest: beer
drink_biggest: sake
drink_lightest: coke
drink_heaviest: flakes
object_smallest: tea
object_biggest: bag
object_lightest: glass
object_heaviest: beer
candies_smallest: mints
candies_biggest: manju
candies_lightest: mints
candies_heaviest: chocolate_bar
toiletries_smallest: soap
toiletries_biggest: shampoo
toiletries_lightest: cloth
toiletries_heaviest: shampoo
containers_smallest: bag
containers_biggest: box
containers_lightest: glass
containers_heaviest: box
snacks_smallest: peanuts
snacks_biggest: senbei
snacks_lightest: chips
snacks_heaviest: senbei
