# classes: ['toiletries', 'snacks', 'fruits', 'cutlery', 'tableware', 'food', 'drinks', 'containers', 'cupboardfood', 'cabinetfood']
classes: ['cleaning_stuff', 'snacks', 'fruits', 'drinks', 'containers','food', 'cutlery', 'tableware'] #'cupboardfood', 'cabinetfood']


#Cleaning Stuff: 
cleaning_stuff: ['cloth','scrubby','sponge']
cleaning_stuffs:  ['cloth','scrubby','sponge']
cleaning_stuffs_location: side_table
cleaning_stuff_location: side_table

#Containers: 
containers: ['tray', 'basket']
container: ['tray', 'basket']
containers_location: end_table
container_location: end_table

#Drinks: 
drinks: ['chocolate_drink', 'coke', 'orange_juice', 'grape_juice', 'sprite']
drink: ['chocolate_drink', 'coke', 'orange_juice', 'grape_juice', 'sprite']
drinks_location: counter
drink_location: counter

#Food: Location TBA
food: [ 'cereal', 'noodles', 'sausage']
food_location: cupboard
#cupboardfood: []
#cabinetfood: []
#cupboardfood_location: cupboard
#cabinetfood_location: cabinet

#Fruits: 
fruits: ['apple','orange','paprika']
fruit: ['apple','orange','paprika']
fruits_location: bookcase
fruit_location: bookcase

#Cutlery
cutlery: ['fork','knife','spoon']
cutlery_location: storage_table

#Tabletware
tableware: ['bowl','cup','dish']
tablewares: ['bowl','cup','dish']
tablewares_location: storage_table
tableware_location: storage_table

#Snacks : 
snacks: ['crackers', 'potato_chips', 'pringles']
snack:  ['crackers', 'potato_chips', 'pringles']
snacks_location: bookcase
snack_location: bookcase

unknown: []
unknown_location: waste_bin


small_object: ['cloth', 'scrubby', 'sponge', 'basket', 'tray', 'chocolate_drink', 'coke', 'orange_juice', 'grape_juice', 'sprite', 'cereal', 'noodles', 'sausage', 'apple', 'orange', 'paprika', 'crackers', 'potato_chips', 'pringles','bowl','cup','fork','knife','dish','spoon']
small_objects: ['cloth', 'scrubby', 'sponge', 'basket', 'tray', 'chocolate_drink', 'coke', 'orange_juice', 'grape_juice', 'sprite', 'cereal', 'noodles', 'sausage', 'apple', 'orange', 'paprika', 'crackers', 'potato_chips', 'pringles','bowl','cup','fork','knife','dish','spoon']

classes_colour : ['blue','red','yellow','black','white','grey','green','brown','pink','orange']
blue: ['sausage']
red: ['coke', 'apple','paprika']
yellow: ['scrubby','cereal']
black: ['potato_chips']
white: ['basket', 'tray', 'orange_juice', 'grape_juice','noodles']
grey: []
green: ['sprite','pringles','bowl','cup','fork','knife','dish','spoon']
brown: ['chocolate_drink']
pink: ['sponge']
orange: ['cloth', 'orange','crackers']

size : ['cloth', 'scrubby', 'sponge', 'basket', 'tray', 'chocolate_drink', 'coke', 'orange_juice', 'grape_juice', 'sprite', 'cereal', 'noodles', 'sausage', 'apple', 'orange', 'paprika', 'crackers', 'potato_chips', 'pringles','bowl','cup','fork','knife','dish','spoon']
weigth : ['cloth', 'scrubby', 'sponge', 'basket', 'tray', 'chocolate_drink', 'coke', 'orange_juice', 'grape_juice', 'sprite', 'cereal', 'noodles', 'sausage', 'apple', 'orange', 'paprika', 'crackers', 'potato_chips', 'pringles','bowl','cup','fork','knife','dish','spoon']

unknown_class: unknown

#FIRST VERSION - NO WEIGHT - NO SIZE
cleaning_stuff_smallest:  'cloth'
cleaning_stuff_biggest: 'scrubby'
cleaning_stuff_lightest: 'cloth'
cleaning_stuff_heaviest: 'scrubby'

container_smallest: 'tray'
container_biggest: 'basket'
container_lightest: 'tray'
container_heaviest: 'basket'
containers_smallest: 'tray'
containers_biggest: 'basket'
containers_lightest: 'tray'
containers_heaviest: 'basket'

cutlery_smallest: 'cup'
cutlery_biggest: 'dish'
cutlery_lightest: 'cup'
cutlery_heaviest: 'bowl'

drinks_smallest: 'coke'
drink_smallest: 'sprite'
drinks_biggest:  'chocolate_drink'
drink_biggest: 'chocolate_drink'
drinks_lightest: 'coke'
drink_lightest: 'sprite'
drinks_heaviest: 'chocolate_drink'
drink_heaviest: 'chocolate_drink' 

food_smallest: 'sausage'
food_biggest: 'noodles'
food_lightest: 'cereal'
food_heaviest: 'sausage'

fruit_smallest: 'orange'
fruit_biggest: 'paprika'
fruit_lightest: 'paprika'
fruit_heaviest: 'apple'
fruits_smallest: 'orange'
fruits_biggest: 'paprika'
fruits_lightest: 'paprika'
fruits_heaviest: 'apple'

snack_smallest: 'crackers'
snack_biggest: 'potato_chips'
snack_lightest: 'crackers'
snack_heaviest: 'pringles'
snacks_smallest: 'crackers'
snacks_biggest: 'potato_chips'
snacks_lightest: 'crackers'
snacks_heaviest: 'pringles'

tableware_smallest: 'spoon'
tableware_biggest: 'knife'
tableware_lightest: 'spoon'
tableware_heaviest: 'knife'

object_smallest: 'cloth'
object_biggest: 'tray'
object_lightest: 'cloth'
object_heaviest: 'pringles'
objects_smallest: 'cloth'
objects_biggest: 'tray'
objects_lightest: 'cloth'
objects_heaviest: 'pringles'


places: ['bedroom', 'dining_room', 'living_room', 'kitchen', 'corridor']

# BIG OBJECT and Manipulation places TBA
bedroom: ['bed', 'desk', 'side_table']
dining_room: ['dining_table']
living_room: ['bookcase', 'couch', 'end_table','lamp']
kitchen: ['cupboard', 'counter','dishwasher', 'sink','storage_table']
corridor: []

bed : []
desk: []
side_table: []
dining_table: []
bookcase: []
couch: []
end_table: []
lamp: []
cupboard: []
counter: []
dishwasher: []
sink: []
storage_table: []

#BIG OBJECT AND MANIPULATION TBA
big_object: ['bed', 'desk', 'side_table','dining_table','bookcase', 'couch', 'end_table','lamp','cupboard', 'counter','dishwasher', 'sink','storage_table']
big_objects: ['bed', 'desk', 'side_table','dining_table','bookcase', 'couch', 'end_table','lamp','cupboard', 'counter','dishwasher', 'sink','storage_table']

bedroom_doors: '1'
kitchen_doors: '1'    
living_room_doors: '1'
dining_room_doors: '0'
corridor_doors: '1'

# TABLES AND CHAIRS TBA
bedroom_table: '1'
kitchen_table: '1'
living_room_table: '1'
corridor_table: '0'
dining_room_table: '1'

bedroom_chairs: '1'
kitchen_chairs: '0'
living_room_chairs: '0'
corridor_chairs: '0'
dining_room_chairs: '2'