# classes: ['toiletries', 'snacks', 'fruits', 'cutlery', 'tableware', 'food', 'drinks', 'containers', 'cupboardfood', 'cabinetfood']
classes: ['cleaning_stuff', 'snacks', 'fruits', 'drinks', 'containers','food'] #'cupboardfood', 'cabinetfood']


#Cleaning Stuff: location: TBA
cleaning_stuff: ['cloth','scrubby','sponge']
cleaning_stuffs:  ['cloth','scrubby','sponge']
cleaning_stuffs_location: center_table
cleaning_stuff_location: center_table

#Containers: location: TBA
containers: ['tray', 'basket']
container: ['tray', 'basket']
containers_location: counter
container_location: counter

#Drinks: Location TBA
drinks: ['chocolate_drink', 'coke', 'orange_juice', 'grape_juice', 'sprite']
drink: ['chocolate_drink', 'coke', 'orange_juice', 'grape_juice', 'sprite']
drinks_location: fridge
drink_location: fridge

#Food: Location TBA
food: [ 'cereal', 'noodles', 'sausage']
food_location: cupboard_and_cabinet
#cupboardfood: []
#cabinetfood: []
#cupboardfood_location: cupboard
#cabinetfood_location: cabinet

#Fruits: location TBA
fruits: ['apple','orange','paprika']
fruit: ['apple','orange','paprika']
fruits_location: dining_table
fruit_location: dining_table

#Snacks : location: TBA
snacks: ['crackers',  'potato_chips', 'pringles']
snack:  ['crackers',  'potato_chips', 'pringles']
snacks_location: center_table
snack_location: center_table

unknown: []
unknown_location: waste_bin


small_object: ['cloth', 'scrubby', 'sponge', 'basket', 'tray', 'chocolate_drink', 'coke', 'orange_juice', 'grape_juice', 'sprite', 'cereal', 'noodles', 'sausage', 'apple', 'orange', 'paprika', 'crackers', 'potato_chips', 'pringles']
small_objects: ['cloth', 'scrubby', 'sponge', 'basket', 'tray', 'chocolate_drink', 'coke', 'orange_juice', 'grape_juice', 'sprite', 'cereal', 'noodles', 'sausage', 'apple', 'orange', 'paprika', 'crackers', 'potato_chips', 'pringles']

classes_colour : ['blue','red','yellow','black','white','grey','green','brown','pink','orange']
blue: ['sausage']
red: ['coke', 'apple','paprika']
yellow: ['scrubby','cereal']
black: ['potato_chips']
white: ['basket', 'tray', 'orange_juice', 'grape_juice','noodles']
grey: []
green: ['sprite','pringles']
brown: ['chocolate_drink']
pink: ['sponge']
orange: ['cloth', 'orange','crackers']

size : ['cloth', 'scrubby', 'sponge', 'basket', 'tray', 'chocolate_drink', 'coke', 'orange_juice', 'grape_juice', 'sprite', 'cereal', 'noodles', 'sausage', 'apple', 'orange', 'paprika', 'crackers', 'potato_chips', 'pringles']
weigth : ['cloth', 'scrubby', 'sponge', 'basket', 'tray', 'chocolate_drink', 'coke', 'orange_juice', 'grape_juice', 'sprite', 'cereal', 'noodles', 'sausage', 'apple', 'orange', 'paprika', 'crackers', 'potato_chips', 'pringles']

unknown_class: unknown

#FIRST VERSION - NO WEIGHT - NO SIZE
cleaning_stuff_smallest:  cloth'
cleaning_stuff_biggest: 'scrubby'
cleaning_stuff_lightest: 'cloth'
cleaning_stuff_heaviest: 'scrubby'

container_smallest: 'tray'
container_biggest: 'basket'
container_lightest: 'tray'
container_heaviest: 'basket'
containers_smallest: 'tray'
containers_biggest: 'basket'
containers_lightest: 'tray'
containers_heaviest: 'basket'

drinks_smallest: 'coke'
drink_smallest: 'sprite'
drinks_biggest:  'chocolate_drink'
drink_biggest: 'chocolate_drink'
drinks_lightest: 'coke'
drink_lightest: 'sprite'
drinks_heaviest: 'chocolate_drink'
drink_heaviest: 'chocolate_drink' 

food_smallest: 'sausage'
food_biggest: 'noodles'
food_lightest: 'cereal'
food_heaviest: 'sausage'

fruit_smallest: 'orange'
fruit_biggest: 'paprika'
fruit_lightest: 'paprika'
fruit_heaviest: 'apple'
fruits_smallest: 'orange'
fruits_biggest: 'paprika'
fruits_lightest: 'paprika'
fruits_heaviest: 'apple'

snack_smallest: 'crackers'
snack_biggest: 'potato_chips'
snack_lightest: 'crackers'
snack_heaviest: 'pringles'
snacks_smallest: 'crackers'
snacks_biggest: 'potato_chips'
snacks_lightest: 'crackers'
snacks_heaviest: 'pringles'

object_smallest: 'cloth'
object_biggest: 'tray'
object_lightest: 'cloth'
object_heaviest: 'pringles'

places: ['bedroom', 'dining_room', 'living_room', 'kitchen', 'corridor']

# BIG OBJECT and Manipulation places TBA
bedroom: ['bed', 'night_table', 'wardrobe', 'dresser', 'armchair', 'drawer', 'desk']
dining_room: ['sideboard', 'cutlery_drawer', 'dining_table', 'chair', 'baby_chair']
living_room: ['bookshelf', 'sofa', 'coffee_table', 'center_table', 'bar', 'fireplace', 'tv_couch']
kitchen: ['microwave', 'cupboard', 'counter', 'cabinet', 'sink', 'stove', 'fridge', 'freezer', 'washing_machine', 'dishwasher']
corridor: ['cabinet']

stove: []
microwave: []
washbasin: []
sink: []
freezer: []
bidet: []
shower: []
toilet: []
towel_rail: []
washbasin: []
cupboard: []
sink: []
stove: []
washing_machine: []
dishwasher: []
bookshelf: []
sofa: []
coffee_table: []
bar: []
fireplace: []
tv_couch: []
chair: []
baby_chair: []
bed: []
night_table: []
wardrobe: []
dresser: []
armchair: []
drawer: []
desk: []

#BIG OBJECT AND MANIPULATION TBA
big_object: ['washbasin','bathrooms_cabinet','towel_rail','toilet','bathtub','shower','bidet','dishwasher','washing_machine','freezer','stove','sink','counter','microwave','tv_couch','fireplace','bar','center_table','bookshelf','baby_chair','chair','dining_table','cutlery_drawer','drawer','armchair','dresser','wardrobe','night_table','cupboard','bedside','cabinet','little_desk','teepee','bed','sideboard','kitchen_table','kitchen_shelf','kitchen_counter','fridge','kitchen_rack','desk','left_rack','right_rack','bookcase','sofa','coffee_table','TV','bistro_table','left_planks','right_planck','balcony_shelf','entrance_shelf']
big_objects: ['washbasin','bathrooms_cabinet','towel_rail','toilet','bathtub','shower','bidet','dishwasher','washing_machine','freezer','stove','sink','counter','microwave','tv_couch','fireplace','bar','center_table','bookshelf','baby_chair','chair','dining_table','cutlery_drawer','drawer','armchair','dresser','wardrobe','night_table','cupboard','bedside','cabinet','little_desk','teepee','bed','sideboard','kitchen_table','kitchen_shelf','kitchen_counter','fridge','kitchen_rack','desk','left_rack','right_rack','bookcase','sofa','coffee_table','TV','bistro_table','left_planks','right_planck','balcony_shelf','entrance_shelf']

bedroom_doors: '1'
kitchen_doors: '1'    
living_room_doors: '1'
dining_room_doors: '0'
corridor_doors: '1'

# TABLES AND CHAIRS TBA
bedroom_table: '0'
kitchen_table: '1'
living_room_table: '1'
corridor_table: '0'
dining_room_table: '0'

bedroom_chairs: '0'
kitchen_chairs: '6'
living_room_chairs: '0'
corridor_chairs: '0'
dining_room_chairs: '0'