classes: ['toiletries', 'snacks', 'fruits', 'cutlery', 'tableware', 'food', 'drinks', 'containers']

toiletries: ['shampoo', 'soap', 'cloth', 'sponge', 'tooth_paste']
toiletries_location: bathroom_cabinet
toiletrie_location: bathroom_cabinet

snacks: ['chips', 'm_and_m', 'pringles', 'cookies']
snack:  ['chips', 'm_and_m', 'pringles', 'cookies']
snacks_location: center_table
snack_location: center_table


fruits: ['apple','melon', 'banana', 'pear', 'peach']
fruits_location: dining_table
fruit_location: dining_table

cutlery: ['tea_spoon', 'spoon', 'fork', 'knife', 'napkin']
cutlery_location: cutlery_drawer

tableware: ['bid_dish', 'small_dish', 'bowl', 'glass', 'mug']
tableware_location: sideboard

food: ['pasta', 'noodles', 'tuna_fish', 'pickles', 'choco_flakes', 'robo_o', 'muesli']
food_location: cabinet

drinks: ['tea', 'beer', 'coke', 'water', 'milk']
drinks_location: fridge
drink_location: fridge

containers: ['tray', 'box', 'bag']
containers_location: counter
container_location: counter

unknown: []
unknown_location: waste_bin
cleaning_stuff_location: right_rack


places: ['bedroom', 'dining_room', 'living_room', 'kitchen', 'corridor', 'bathroom']

bedroom: ['bed', 'night_table', 'wardrobe', 'dresser', 'armchair', 'drawer', 'desk']
dining_room: ['sideboard', 'cutlery_drawer', 'dining_table', 'chair', 'baby_chair']
living_room: ['bookshelf', 'sofa', 'coffee_table', 'center_table', 'bar', 'fireplace', 'tv_coach']
kitchen: ['microwave', 'cupboard', 'counter', 'cabinet', 'sink', 'stove', 'fridge', 'ferezer', 'washing_machine', 'dishwasher']
corridor: ['cabinet']
bathroom: ['bidet', 'shower', 'bathtub', 'toilet', 'towel_rail', 'bathrooms_cabinet', 'washbasin']

big_object: ['cupboard','bedside','cabinet','little_desk','teepee','bed','sideboard','kitchen_table','kitchen_shelf','kitchen_counter','fridge','kitchen_rack','desk','left_rack','right_rack','bookcase','sofa','coffee_table','TV','bistro_table','left_planks','right_planck','balcony_shelf','entrance_shelf']
big_objects: ['cupboard','bedside','cabinet','little_desk','teepee','bed','sideboard','kitchen_table','kitchen_shelf','kitchen_counter','fridge','kitchen_rack','desk','left_rack','right_rack','bookcase','sofa','coffee_table','TV','bistro_table','left_planks','right_planck','balcony_shelf','entrance_shelf']

bedroom_doors: '1'
kitchen_doors: '1'    
living_room_doors: '1'
balcony_doors: '0'
corridor_doors: '0'
entrance_doors: '1'
bathroom_doors: '1'

bedroom_table: '0'
kitchen_table: '1'
living_room_table: '1'
balcony_table: '1'
corridor_table: '0'
entrance_table: '0'
bathroom_table: '0'

bedroom_chairs: '0'
kitchen_chairs: '6'
living_room_chairs: '0'
balcony_chairs: '2'
corridor_chairs: '0'
entrance_chairs: '0'
bathroom_chairs: '1'

classes_colour : ['blue','red','yellow','black','white']
blue: ['hair_spray','cold_brew','shampoo','cup_star']
red: ['fries','apple','asience','bowl','bread','candy']
yellow: ['green_tea','onion','orange','corn']
black: ['coke','soup_container','jelly']
white: ['aquarius','moisturizer','radish','chewing_gum','chopsticks','curry','fork','spoon','plate']


size : ['spoon','fork','chopsticks','apple','onion','orange','candy','soup_container','chewing_gum','cold_brew','mug','melon','coke','cloth','hair_spray','cup_star','robo_o','fries','asience','jelly','radish','curry','corn','moisturizer','bread','bowl','green_tea','shampoo','aquarius','plate']
weigth : ['fork','spoon','chopsticks','onion','apple','orange','candy','cloth','soup_container','chewing_gum','mug','cold_brew','coke','hair_spray','cup_star','robo_o','fries','asience','radish','bread','curry','corn','jelly','moisturizer','bowl','green_tea','plate','shampoo','aquarius','melon']

unknown_class: unknown

drinks_smallest: 'cold_brew'
drinks_biggest:  'aquarius'
drink_biggest: 'aquarius'
drinks_lightest: 'cold_brew'
drinks_heaviest: 'aquarius' 

food_smallest: 'onion'
food_biggest: 'bread'
food_lightest: 'onion'
food_heaviest: 'radish'

snack_smallest: 'candy'
snack_biggest: 'bread'
snack_lightest: 'fries'
snack_heaviest: 'radish'

cutlery_smallest: 'spoon'
cutlery_biggest: 'chopsticks'
cutlery_lightest: 'forks'
cutlery_heaviest: 'chopsticks'

container_smallest: 'soup_container'
container_biggest: 'plate'
container_lightest: 'soup_container'
container_heaviest: 'bowl'

cleaning_stuff_smallest:  'shampoo'
cleaning_stuff_biggest: 'shampoo'
cleaning_stuff_lightest: 'shampoo'
cleaning_stuff_heaviest: 'shampoo'

fruit_smallest: 'apple'
fruit_biggest: 'orange'
fruit_lightest: 'apple'
fruit_heaviest: 'orange'

object_smallest: 'spoon'
object_biggest: 'plate'
object_lightest: 'fork'
object_heaviest: 'aquarius'
