classes : ['drinks','food','snacks','cutlery','containers','cleaning_stuff','fruit']
unknown: []
drinks: ['aquarius','coke','cold_brew','green_tea']
food: ['bread','corn','onion','radish']
snacks: ['candy','chewing_gum','cup_star','curry','fries','jelly']
candies: ['candy','chewing_gum','cup_star','curry','fries','jelly']
cutlery: ['chopsticks','fork','spoon']
containers: ['bowl','plate','soup_container']
cleaning_stuff: ['asience','hair_spray','moisturizer','shampoo']
fruit: ['apple','orange']
toiletries: ['paper']

office_doors: '3'

unknown_location: waste_bin
drinks_location: kitchen_counter
food_location: kitchen_shelf
snack_location: kitchen_rack
cutlery_location: sideboard
container_location: left_rack
cleaning_stuff_location: right_rack
fruit_location: balcony_shelf
drink_location: kitchen_counter
snacks_location: kitchen_rack
containers_location: left_rack
toiletries_location: furniture



places: ['bedroom','kitchen','living','balcony','corridor','entrance','bathroom', 'office']
bedroom: ['little_desk','teepee','bed', 'bedside']
kitchen: ['sideboard','kitchen_table','kitchen_shelf','kitchen_counter','fridge','kitchen_rack', 'cupboard', 'dining_table']
living: ['desk','left_rack','right_rack','bookcase','sofa','coffee_table','TV', 'cabinet', 'center_table','baby_chair']
balcony: ['bistro_table','left_planks','right_planck','balcony_shelf']
corridor: []
entrance: ['entrance_shelf']
bathroom: ['furniture']
office: ['bar']

bedside: []
dining_table: []
cupboard: ['paper']
center_table: []
cabinet: []
bar: []

 
big_object: ['cupboard','bedside','cabinet','little_desk','teepee','bed','sideboard','kitchen_table','kitchen_shelf','kitchen_counter','fridge','kitchen_rack','desk','left_rack','right_rack','bookcase','sofa','coffee_table','TV','bistro_table','left_planks','right_planck','balcony_shelf','entrance_shelf']
big_objects: ['cupboard','bedside','cabinet','little_desk','teepee','bed','sideboard','kitchen_table','kitchen_shelf','kitchen_counter','fridge','kitchen_rack','desk','left_rack','right_rack','bookcase','sofa','coffee_table','TV','bistro_table','left_planks','right_planck','balcony_shelf','entrance_shelf']

bedroom_doors: '1'
kitchen_doors: '1'    
living_doors: '1'
balcony_doors: '0'
corridor_doors: '0'
entrance_doors: '1'
bathroom_doors: '1'

bedroom_table: '0'
kitchen_table: '1'
living_table: '1'
balcony_table: '1'
corridor_table: '0'
entrance_table: '0'
bathroom_table: '0'

bedroom_chairs: '0'
kitchen_chairs: '6'
living_chairs: '0'
balcony_chairs: '2'
corridor_chairs: '0'
entrance_chairs: '0'
bathroom_chairs: '1'


bedroom_bedside: '1'


classes_colour : ['blue','red','yellow','black','white']
blue: ['hair_spray','cold_brew','shampoo','cup_star']
red: ['fries','apple','asience','bowl','bread','candy']
yellow: ['green_tea','onion','orange','corn']
black: ['coke','soup_container','jelly']
white: ['aquarius','moisturizer','radish','chewing_gum','chopsticks','curry','fork','spoon','plate']


size : ['spoon','fork','chopsticks','apple','onion','orange','candy','soup_container','chewing_gum','cold_brew','coke','hair_spray','cup_star','fries','asience','jelly','radish','curry','corn','moisturizer','bread','bowl','green_tea','shampoo','aquarius','plate']
weigth : ['fork','spoon','chopsticks','onion','apple','orange','candy','soup_container','chewing_gum','cold_brew','coke','hair_spray','cup_star','fries','asience','radish','bread','curry','corn','jelly','moisturizer','bowl','green_tea','plate','shampoo','aquarius']

unknown_class: unknown

drinks_smallest: 'cold_brew'
drinks_biggest:  'aquarius'
drink_biggest: 'aquarius'
drinks_lightest: 'cold_brew'
drinks_heaviest: 'aquarius' 

food_smallest: 'onion'
food_biggest: 'bread'
food_lightest: 'onion'
food_heaviest: 'radish'

snack_smallest: 'candy'
snack_biggest: 'bread'
snack_lightest: 'fries'
snack_heaviest: 'radish'

cutlery_smallest: 'spoon'
cutlery_biggest: 'chopsticks'
cutlery_lightest: 'forks'
cutlery_heaviest: 'chopsticks'

container_smallest: 'soup_container'
container_biggest: 'plate'
container_lightest: 'soup_container'
container_heaviest: 'bowl'

cleaning_stuff_smallest:  'shampoo'
cleaning_stuff_biggest: 'shampoo'
cleaning_stuff_lightest: 'shampoo'
cleaning_stuff_heaviest: 'shampoo'

fruit_smallest: 'apple'
fruit_biggest: 'orange'
fruit_lightest: 'apple'
fruit_heaviest: 'orange'

object_smallest: 'spoon'
object_biggest: 'plate'
object_lightest: 'fork'
object_heaviest: 'aquarius'




