#Cylinder :::> name : [diameter(scale.x =scale.y), height (scale.z) ]
apple: [ 0.06, 0.05]
aquarius: [ 0.17, 0.08]
asience: [ 0.17, 0.05]
bowl: [ 0.15, 0.15] #TODO train
bread: [ 0.13, 0.11]
candy: [ 0.08, 0.04]
chewing_gum: [ 0.08, 0.06]
chopsticks: [ 0.15, 0.15] #TODO train
coke: [ 0.14, 0.05]
cold_brew: [ 0.13, 0.06]
corn: [ 0.06, 0.18]
cup_star: [ 0.11, 0.08]
curry: [ 0.11, 0.08] 
fork: [ 0.15, 0.15] #TODO train
fries: [ 0.14, 0.06]
green_tea: [ 0.19, 0.06]
hair_spray: [ 0.20, 0.05]
jelly: [ 0.06, 0.09]
moisturizer: [ 0.16, 0.03]
onion: [ 0.06, 0.06]
orange: [ 0.15, 0.15] #TODO train
plate: [ 0.15, 0.15] #TODO train
radish: [ 0.16, 0.08]
shampoo: [ 0.17, 0.04]
soup_container: [ 0.15, 0.15]#TODO train
spoon: [ 0.10, 0.01] #TODO train