apple: ['fruit', 0.15, 0.15]
bag: ['container', 0.15, 0.15]
banana_milk: ['drink', 0.15, 0.15]
basket: ['container', 0.15, 0.15]
bread: ['food', 0.15, 0.15]
cappucino: ['drink', 0.15, 0.15]
cereals: ['food', 0.15, 0.15]
chocolate_cookies: ['snack', 0.15, 0.15]
cloth: ['cleaning_stuff', 0.15, 0.15]
coffeecup: ['container', 0.15, 0.15]
coke: ['drink', 0.15, 0.15]
cornflakes: ['food', 0.15, 0.15]
crackers: ['food', 0.15, 0.15]
egg: ['snack', 0.15, 0.15]
fork: ['cutlery', 0.15, 0.15]
spoon: ['cutlery', 0.15, 0.15]
knife: ['cutlery', 0.15, 0.15]
lemon: ['fruit', 0.15, 0.15]
noodles: ['food', 0.15, 0.15]
orange_drink: ['drink', 0.15, 0.15]
paper: ['cleaning_stuff', 0.15, 0.15]
paprika: ['food', 0.15, 0.15]
party_cracker: ['snack', 0.15, 0.15]
pear: ['fruit', 0.15, 0.15]
peas: ['food', 0.15, 0.15]
pepper: ['food', 0.15, 0.15]
plate: ['container', 0.15, 0.15]
potato: ['food', 0.15, 0.15]
potato_soup: ['food', 0.15, 0.15]
pringles: ['snack', 0.15, 0.15]
red_bowl: ['container', 0.15, 0.15]
salt: ['food', 0.15, 0.15]
sponge: ['cleaning_stuff', 0.15, 0.15]
tomato_pasta: ['food', 0.15, 0.15]
towel: ['cleaning_stuff', 0.15, 0.15]
water: ['drink', 0.15, 0.15]
white_bowl: ['container', 0.15, 0.15]
