#Cylinder :::> name : [diameter(scale.x =scale.y), height (scale.z) ]
banana_milk: [ 0.08, 0.25]
cappucino: [ 0.07, 0.17]
noodles: [ 0.1, 0.105]
orange_drink: [ 0.06, 0.12]
peas: [ 0.09, 0.12]
pringles: [ 0.08, 0.21]
water: [ 0.08, 0.21]
yogurt: [ 0.08, 0.25]

white_bowl: [ 0.15, 0.15]
apple: [ 0.15, 0.15]
bag: [ 0.15, 0.15]
basket: [ 0.15, 0.15]
bread: [ 0.15, 0.15]
cereals: [ 0.15, 0.15]
chocolate_cookies: [ 0.15, 0.15]
cloth: [ 0.15, 0.15]
coffeecup: [ 0.15, 0.15]
coke: [ 0.15, 0.15]
cornflakes: [ 0.15, 0.15]
crackers: [ 0.15, 0.15]
egg: [ 0.15, 0.15]
fork: [ 0.15, 0.15]
spoon: [ 0.15, 0.15]
knife: [ 0.15, 0.15]
lemon: [ 0.15, 0.15]
paper: [ 0.15, 0.15]
paprika: [ 0.15, 0.15]
party_cracker: [ 0.15, 0.15]
pear: [ 0.15, 0.15]
pepper: [ 0.15, 0.15]
plate: [ 0.15, 0.15]
potato: [ 0.15, 0.15]
potato_soup: [ 0.15, 0.15]
red_bowl: [ 0.15, 0.15]
salt: [ 0.15, 0.15]
sponge: [ 0.15, 0.15]
tomato_pasta: [ 0.15, 0.15]
towel: [ 0.15, 0.15]