#Cylinder :::> name : [diameter(scale.x =scale.y), height (scale.z) ]
cloth: [ 0.05, 0.06]
scrubby: [ 0.08, 0.17]
sponge: [ 0.05, 0.17]
basket: [ 0.15, 0.15] #TODO train
tray: [ 0.11, 0.13]
chocolate_drink: [ 0.04, 0.08]
coke: [ 0.06, 0.08]
orange_juice: [ 0.02, 0.05]
grape_juice: [ 0.05, 0.14]
sprite: [ 0.06, 0.13]
cereal: [ 0.18, 0.06]
noodles: [ 0.08, 0.1]
sausage: [ 0.09, 0.11]
apple: [ 0.15, 0.15] #TODO train
orange: [ 0.06, 0.14]
paprika: [ 0.06, 0.19]
crackers: [ 0.05, 0.20]
potato_chips: [ 0.09, 0.06]
pringles: [ 0.03, 0.16]
bowl: [ 0.06, 0.06]
cup: [ 0.05, 0.05]
fork: [ 0.15, 0.15] #TODO train
knife: [ 0.08, 0.16]