dinner_table: [ 0.8, 0.6, 0.6]
kitchen_counter: [ 0.8, 0.6, 0.6]
sofa: [ 0.8, 0.6, 0.6]
couch_table: [ 0.8, 0.6, 0.6]
side_table: [ 0.8, 0.6, 0.6]
stove: [ 0.8, 0.6, 0.6]
bed: [ 0.8, 0.6, 0.6]
closet: [ 0.8, 0.6, 0.6]
desk: [ 0.8, 0.6, 0.6]
